spring.application.name=ff-server
spring.config.import=classpath:datasource.properties

spring.quartz.job-store-type=jdbc
spring.datasource.url=${datasource.url}
spring.datasource.driver-class-name=${datasource.driver}
spring.datasource.username=${datasource.user}
spring.datasource.password=${datasource.password}
spring.jpa.database-platform=${datasource.platform}
spring.quartz.jdbc.initialize-schema=always

spring.jpa.hibernate.ddl-auto=update